# Generated by Django 6.0.5 on 2026-05-24 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'SCOPE_1'), ('SCOPE_2', 'SCOPE_2'), ('SCOPE_3', 'SCOPE_3')], max_length=20)),
                ('activity_value', models.FloatField()),
                ('activity_unit', models.CharField(max_length=50)),
                ('co2e_kg', models.FloatField()),
                ('status', models.CharField(choices=[('VALID', 'VALID'), ('WARNING', 'WARNING'), ('FAILED', 'FAILED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='VALID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.emissionrecord')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization'),
        ),
    ]
